#!/bin/bash

add_tag() {
	tag=$1
	echo "Adding tag ${tag}"
	docker tag ${IMAGE_NAME} ${DOCKER_REPO}:${tag}
	docker push ${DOCKER_REPO}:$tag
}


for tag in $(grep "tags=" Dockerfile | cut -d'"' -f2); do
	add_tag ${tag}
done
